export interface PortfolioItem {
  id: string;
  title: string;
  category: string;
  image: string;
  assets?: string[]; // Array of all related images/videos for detail view
  description: string;
  brand: string;
  industry: string;
  duration: string;
  count?: number;
  featured?: boolean;
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: "genesis",
    title: "GENESIS",
    category: "BRAND LAUNCH",
    image: "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.001.webp",
    assets: [
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.001.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.002.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.003.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.004.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.005.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.006.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.007.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.008.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.009.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.010.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.011.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.012.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.013.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.014.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.015.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.016.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.017.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.018.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.019.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.020.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.021.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.022.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.023.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.024.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.025.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.026.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.027.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.028.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.029.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.030.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.031.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.032.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.033.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.034.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.035.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.036.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.037.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.038.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.039.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.040.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.041.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.042.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.043.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.044.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.045.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.046.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.047.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.048.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.049.webp",
      "/attached_assets/1. GENESIS Treatment_FOR WEBSITE/GENESIS Brand Launch Event_Pitch Deck_V2.050.webp"
    ],
    description: "The Genesis brand is a new beginning, a testament to a thoughtful, minimalist approach to luxury. It is a philosophy that seeks to defy the ostentatious and embrace a new sense of elegance. This film is symbolic of the brand's promise to deliver a pure, uncompromised experience.\n\nThis story, as simple and elegant as it was, was just as revelatory. In it, we follow a creative individual, a master of their craft, on a journey of discovery. They are not chasing the obvious or the extravagant, but rather seeking the perfect balance between form and function. Each moment, each decision, is a testament to their dedication, stretching their creative limits. But they persevere, and lo and behold! Their vision manifests on one unassuming day. And by their side, living every moment with them from start to finish, is their trusty Genesis.\n\nThe director really wanted to capture the essence of a clean slate for this one. This film is a character piece, both of the creative and the Genesis, so it was our binding duty to create an overall mood & tone for the treatment that was inherently fresh and authentic. It had to live up to the visceral nature of the world the script had made. It had to feel like the protagonist had no one to watch their back, but themselves in the vast, open spaces. We wanted the viewer to experience every second with them; to bear the thoughtfulness of the unrelenting journey and feel the pain of their failures to find the perfect expression. This would ultimately result in a beautiful, emotional payoff and hearten the viewers to join in on the protagonist's win and jubilation.",
    brand: "Genesis Motors",
    industry: "Automotive",
    duration: "3 days",
    count: 50,
    featured: true
  },
  {
    id: "acuvue",
    title: "ACUVUE",
    category: "HEALTHCARE",
    image: "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_1.webm",
    assets: [
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_1.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_2.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_3.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_4.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_5.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_6.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_7.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_8.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_9.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_10.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_11.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_12.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_13.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_14.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_15.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_16.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_17.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_18.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_19.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_20.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_21.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_22.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_23.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_24.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_25.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_26.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_27.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_28.webm",
      "/attached_assets/2. ACUVUE Treatment_FOR WEBSITE/ACUVUE_29.webm"
    ],
    description: "This film is a celebration of clarity, freedom, and possibility — a high-energy journey where vision becomes the key to conquering life. With Acuvue Oasys, every horizon opens, every challenge feels within reach, and every moment is sharper, brighter, and more alive.\n\nWe follow our Gen-Z Korean protagonist — a jewellery designer, athlete, and dreamer — as she pushes her limits on a breathtaking marathon through sweeping landscapes. The split-screen technique becomes our visual heartbeat: one side capturing the exhilaration of her limitless world, the other locking on her eyes — focused, determined, unstoppable. In contrast, runners with glasses experience the subtle frustrations of restricted vision, reinforcing the liberation that Acuvue lenses bring.\n\nThe tone is kinetic yet intimate, fuelled by sweeping camera moves, vibrant Acuvue teal, and sunlight that caresses skin like possibility itself. Every shot pulses with energy, from the wind rushing past her to the gleam in her eye as she crosses the finish line. This is more than a commercial — it's an invitation to see life without limits.",
    brand: "Johnson & Johnson",
    industry: "Healthcare",
    duration: "2 days",
    count: 29,
    featured: true
  },
  {
    id: "la-mer",
    title: "LA MER x ANA DE ARMAS",
    category: "LUXURY BEAUTY",
    image: "/attached_assets/3. LA MER x ANA DE ARMAS Treatment_FOR WEBSITE/LA MER x Ana De Armas_1.webp",
    assets: Array.from({length: 58}, (_, i) => `/attached_assets/3. LA MER x ANA DE ARMAS Treatment_FOR WEBSITE/LA MER x Ana De Armas_${i + 1}.webp`),
    description: "La Mer was an odyssey into surrealism; an imaginarium of visuals charged with symbolism that ultimately bottle up everything that goes into it's Moisturizing Soft Cream. It's intangible beauty is what reels you in.\n\nThe idea was to effectively communicate the feeling of the product through the film's physicality and Ana De Armas' magnetism. We wanted to invoke a feeling of magical synaesthesia in the audience's subconscious and take it to a place beyond the waking mind; to arouse their senses through visual and aural stimulation of the film's fantasy and surrealism.",
    brand: "Estée Lauder",
    industry: "Beauty & Cosmetics",
    duration: "4 days",
    count: 58,
    featured: true
  },
  {
    id: "ford",
    title: "FORD - Make Your Own Normal",
    category: "AUTOMOTIVE",
    image: "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.001.webp",
    assets: [
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.001.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.002.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.003.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.006.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.007.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.008.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.009.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.010.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.011.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.012.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.013.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.014.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.015.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.016.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.017.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.019.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.020.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.021.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.022.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.023.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.024.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.027.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.028.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.030.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.031.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.032.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.033.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.034.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.035.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.036.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.037.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.038.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.039.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.040.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.041.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.042.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.045.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.046.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.047.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.048.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.049.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.050.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.051.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.052.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.054.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.055.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.056.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.057.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.058.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.059.webp",
      "/attached_assets/4. FORD - Make Your Own Normal_FOR WEBSITE/FORD - Make Your Own Normal_Treatment_Initium.060.webp"
    ],
    description: "FORD: Make Your Own Normal is paradigmatic of the phrase 'carpe diem'.\n\nThe treatment for this campaign dictates that no one is wholly what they seem at first sight or encounter. Our identities wear multiple faces and dimensions underneath our physical makeups, and therefore have multiple adventures to experience and stories to share. Life works in unexpected ways, which we must accept and follow without inhibitions or preconceived notions. This film celebrates it all; the trials, the joys, the sorrows, and the wonders of life. No one path is correct and there is no linear route through life, because life moves fast. Very fast. So, don't miss the opportunities it throws your way because they might not come around again.",
    brand: "Ford Motor Company",
    industry: "Automotive",
    duration: "3 days",
    count: 50,
    featured: true
  },
  {
    id: "pantene",
    title: "PANTENE",
    category: "BEAUTY & HAIR CARE",
    image: "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_1.webm",
    assets: [
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_1.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_2.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_3.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_4.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_5.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_6.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_7.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_8.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_9.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_10.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_11.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_12.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_13.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_14.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_15.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_16.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_17.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_18.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_19.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_20.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_21.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_22.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_23.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_24.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_25.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_26.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_27.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_28.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_29.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_30.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_31.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_32.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_33.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_34.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_35.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_36.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_37.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_38.webm",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_39.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_40.webp",
      "/attached_assets/5. PANTENE Treatment_FOR WEBSITE/PANTENE_41.webm"
    ],
    description: "This campaign is a trilogy of cinematic stories where Pantene's promise of confidence, resilience, and transformation comes to life. With Yaya at the heart, each film turns everyday haircare into a moment of beauty, movement, and empowerment — hair that's damage-free, luminous, and full of vitality.\n\nThe visual world is premium yet minimal, defined by Pantene's signature white-and-gold palette, modular set designs, and tactile, symbolic elements — melting golden tools, glowing clocks, and graceful golden lines — each reflecting a unique narrative of repair, time-defiance, or precision. Hair is always the hero: shimmering, strong, and in motion, captured through dynamic camera choreography that feels fluid and alive.\n\nFrom intimate close-ups to sweeping, dance-like movement, the films invite the audience to feel the texture, weight, and shine of Pantene hair. Lighting sculpts every strand, music underscores each transformation, and Yaya's confident presence ties it all together. This is more than haircare — it's a visual celebration of strength and self-assurance, crafted with elegance and intent.",
    brand: "Procter & Gamble",
    industry: "Consumer Goods",
    duration: "2 days",
    count: 41,
    featured: true
  },
  {
    id: "vaseline-hbo",
    title: "VASELINE x HBO",
    category: "COLLABORATION",
    image: "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_1.webm",
    assets: [
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_1.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_2.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_5.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_6.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_7.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_8.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_9.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_11.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_12.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_13.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_15.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_16.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_17.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_18.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_24.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_25.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_26.webm",
      "/attached_assets/6. VASELINE x HBO Treatment_FOR WEBSITE/VXHBO_1080p_27.webm"
    ],
    description: "The Bright Lotus is a lush escape where radiant skin meets radiant living — a cinematic journey inspired by the luxurious storytelling of HBO's The White Lotus. Here, beauty is both the destination and the path, with Vaseline Spotless Glow as the catalyst for transformation.\n\nWe follow Lorena, a spirited traveler, into the sun-soaked paradise of Koh Samui — from the sleek lines of a yacht to the golden-hour elegance of a lilac satin gown. An intimate moment reveals a small shadow on her radiance; with a touch of Vaseline Spotless Glow, confidence returns and the world expands, walls falling away to reveal boundless horizons.\n\nThis is not just skincare — it's a sensory escape. Ambient light, shimmering textures, and natural intimacy draw the viewer in, creating a film that is indulgent yet approachable, elegant yet real. The result is a story that leaves audiences not only seeing the glow, but feeling it.",
    brand: "Unilever x HBO",
    industry: "Consumer Goods",
    duration: "4 days",
    count: 18,
    featured: true
  },
  {
    id: "f1-renault",
    title: "FORMULA 1 X RENAULT SPORT",
    category: "MOTORSPORT",
    image: "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.001.webp",
    assets: [
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.001.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.002.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.003.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.004.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.005.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.006.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.007.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.008.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.009.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.010.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.011.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.012.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.013.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.014.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.015.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.016.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.017.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.018.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.019.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.020.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.021.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.022.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.023.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.024.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.025.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.026.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.027.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.028.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.029.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.030.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.031.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.032.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.033.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.034.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.035.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.036.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.037.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.038.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.039.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.040.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.041.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.042.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.043.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.044.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.045.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.046.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.047.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.048.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.049.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.050.webp",
      "/attached_assets/7. FORMULA 1 x RENAULT SPORT Treatment_FOR WEBSITE/FORMULA 1 : : RENAULT SPORT_Treatment_Initium.051.webp"
    ],
    description: "This was an unusual one for an equally unusual campaign.\n\nIn July 2018, the Kingdom of Saudi Arabia made it legal for women to drive and Renault wanted to beat every other automaker to the punch by staging a grand event in honour of this historic event. Renault Sport and Formula 1, along with Renault's consumer car division, would launch a live rally with Renault's best consumer cars driving through the main streets of Doha headlined by esteemed mountain climber, thrill-seeker and pioneer Raha Moharrak driving an F1 race car. In addition, two commercials showcasing the Renault Koleos and Duster would be screened with Raha endorsing and starring in both.\n\nRenault's main purpose was to be emblematic for the KSA by daring to show the unexpected with its most powerful car; the Formula 1 racer. It wished to demonstrate its determination as an ardent supporter of the women's cause. The campaign was designed for the people, moreover the women, of the KSA. Renault would then broadcast the event live all over the world. This was a talk about human rights, about respect for women, and their perfect ability to drive cars in the future. Through Raha's achievements and popularity, she would be a tour de force and a shining beacon of inspiration for women like no other.\n\nDriving the spectators towards a pure and positive emotion by being delicate and subtle with the subject material was the need of the hour, as this campaign was still a big step for Saudi Arabia's culture.",
    brand: "Renault Sport",
    industry: "Automotive",
    duration: "3 days",
    count: 51,
    featured: true
  },
  {
    id: "hitachi",
    title: "HITACHI SKYLINE",
    category: "TECHNOLOGY",
    image: "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.001.webp",
    assets: [
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.001.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.002.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.003.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.004.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.005.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.006.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.007.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.008.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.009.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.010.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.011.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.012.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.013.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.014.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.015.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.016.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.017.webp",
      "/attached_assets/8. HITACHI Treatment_FOR WEBSITE/HITACHI SKYLINE - Kasiti Sangkul_Director's Treatment_White.018.webp"
    ],
    description: "This film transforms the Hitachi refrigerator into a design statement by weaving its clean, horizontal form into the heart of the storytelling. The \"horizontal line\" becomes our guiding visual motif — shifting, slicing, and framing each scene to subtly direct the viewer's gaze.\n\nJapanese cultural elements flow seamlessly into this language: the meditative geometry of a Zen garden, the quiet elegance of obscured faces, the grandeur of Mount Fuji, the precision of a chef's knife, and the harmony of fine dining plating. Each is staged with meticulous balance, reinforcing both beauty and craftsmanship.\n\nOur protagonist, a dignified middle-aged chef, moves with mastery through his luxurious mountain retreat kitchen. Through elegant compositions — from food preparation to an upside-down dining reveal — we explore precision, artistry, and connection. The final scene introduces a poised love interest, the two sharing a meal as the horizon glows in the distance. The result is a commercial where product, culture, and story align in perfect visual harmony.",
    brand: "Hitachi Ltd.",
    industry: "Technology",
    duration: "2 days",
    count: 18,
    featured: true
  },
  {
    id: "bmw-x3",
    title: "BMW X3",
    category: "LUXURY AUTOMOTIVE",
    image: "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.001.webp",
    assets: [
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.001.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.003.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.004.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.005.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.006.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.007.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.008.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.009.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.010.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.011.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.012.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.013.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.014.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.015.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.016.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.017.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.019.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.020.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.021.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.022.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.023.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.024.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.025.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.026.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.027.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.028.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.029.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.030.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.031.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.032.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.033.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.034.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.035.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.036.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.037.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.038.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.039.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.040.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.041.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.042.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.043.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.044.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.045.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.046.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.047.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.048.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.049.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.050.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.051.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.052.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.053.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.054.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.055.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.056.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.057.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.058.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.059.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.060.webp",
      "/attached_assets/9. BMW X3 Treatment_FOR WEBSITE/BMW X3_WARP SPEED.061.webp"
    ],
    description: "The BMW X3 is a workhorse, the kind that rides with you through every season, braves with you every terrain there is, abides by you during every tribulation. This film is symbolic of the X3's fortitude and solidarity.\n\nThis story, as simple and spartan as it was, it was just as revelatory. In it, we follow a wildlife photographer as he embarks on expedition after expedition in search of the rare and saintly Siberian tiger in the Chinese wilderness. Each time, it eludes him, stretching his will, straining his grit. But he perseveres, and lo and behold! His wish manifests on one unassuming day. And by his side, living every moment with him from start to finish, is his trusty X3.\n\nThe director really wanted to capture the mercilessness of the wilderness for this one. This film is a character piece, both of the photographer and the X3, so it was our binding duty to create an overall mood & tone for the treatment that was inherently raw and natural. It had to live up to the visceral texture of the world the script had forged. It had to feel like the protagonist had no one to watch his back but himself in the wild open spaces. We wanted the viewers to experience every season with him, to bear the harshness of the unrelenting weather and feel the pain of his failures to spot the tiger. This would ultimately result in a beautiful, emotional payoff and hearten the viewers to join in on the protagonist's win and jubilation.",
    brand: "BMW Group",
    industry: "Automotive",
    duration: "4 days",
    count: 59,
    featured: true
  },
  {
    id: "sting",
    title: "STING",
    category: "AUTOMOTIVE",
    image: "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_1.webp",
    assets: [
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_1.webp",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_2.webp",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_3.webp",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_4.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_5.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_6.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_7.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_8.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_9.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_10.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_11.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_12.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_13.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_14.webp",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_15.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_16.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_17.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_18.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_19.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_20.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_21.webm",
      "/attached_assets/10. STING Treatment_FOR WEBSITE/STING_22.webm"
    ],
    description: "Comprehensive high-performance automotive campaign for Nissan STING featuring dynamic cinematography, cutting-edge vehicle technology, and adrenaline-fueled driving sequences through mixed media presentation.",
    brand: "Nissan Motor Company",
    industry: "Automotive",
    duration: "3 days",
    count: 22,
    featured: true
  },









  {
    id: "toyota-beyond-zero",
    title: "TOYOTA: BEYOND ZERO",
    category: "SUSTAINABILITY",
    image: "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.001.webp",
    assets: [
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.001.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.002.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.003.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.004.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.005.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.006.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.007.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.008.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.009.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.010.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.011.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.012.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.013.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.014.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.015.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.016.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.017.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.018.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.019.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.020.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.021.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.022.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.023.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.024.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.025.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.026.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.027.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.028.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.029.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.030.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.031.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.032.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.033.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.034.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.035.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.036.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.037.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.038.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.039.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.040.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.041.webp",
      "/attached_assets/11. TOYOTA - Beyond Zero_FOR WEBSITE/TOYOTA - Beyond Zero_WARP SPEED.042.webp"
    ],
    description: "Comprehensive environmental initiative campaign showcasing Toyota's Beyond Zero vision for carbon neutrality, sustainable mobility solutions, and innovative eco-technology through 42 treatment slides.",
    brand: "Toyota Motor Corporation",
    industry: "Automotive",
    duration: "4 days",
    count: 42,
    featured: true
  },
  {
    id: "bumble",
    title: "BUMBLE",
    category: "DATING APP",
    image: "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.001.webp",
    assets: [
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.001.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.002.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.003.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.004.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.005.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.007.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.008.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.009.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.010.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.012.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.015.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.018.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.019.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.020.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.021.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.022.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.023.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.026.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.027.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.028.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.030.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.031.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.032.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.033.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.034.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.035.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.036.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.037.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.038.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.039.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.040.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.041.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.042.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.043.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.044.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.045.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.046.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.047.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.048.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.049.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.056.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.057.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.058.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.059.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.060.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.061.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.062.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.063.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.064.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.065.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.066.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.067.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.068.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.069.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.070.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.072.webp",
      "/attached_assets/12. BUMBLE Treatment_FOR WEBSITE/BUMBLE_Director's Treatment_May Apizsara_V3.073.webp"
    ],
    description: "In the long history of our species, our traditions have taught women to be modest and inconspicuous. They've been dictated to \"conduct\" or \"carry\" themselves a certain way, to interact with the opposite sex a certain way, to always be led. Bumble challenged that by doing the opposite; daring women to initiate a conversation rather than being initiated into one.\n\nThis story is about the awkwardness of women when they're afraid to make the first move. Given that the film was for the Southeast Asian diaspora, the script reflected the region's ethnic and social culture. The title \"Make The First Move\" aimed at empowering Southeast Asian women to muster up the courage to start a relationship or conversation. This fell within the conduct of the Bumble app and how it encouraged women to make the first move. It opens up a realm of possibilities for women to explore.\n\nThe treatment was designed to focus on the word 'Move' from the film's title. The director was inspired to feel the movement, the fluttering feeling a girl or woman feels during the build-up to a potential romance. The women had charming personalities, ripe with the awkwardness and nervousness of trying to make the first move. The result would be energetic, headlined by these gorgeous ladies and adorned with beautiful art direction, costumes, cinematography and music.",
    brand: "Bumble Inc.",
    industry: "Technology",
    duration: "3 days",
    count: 57,
    featured: true
  },
  {
    id: "downy-saudi",
    title: "DOWNY SAUDI ARABIA",
    category: "REGIONAL CAMPAIGN",
    image: "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_1.webp",
    assets: [
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_1.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_2.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_3.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_4.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_5.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_6.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_7.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_8.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_9.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_10.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_11.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_12.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_13.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_14.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_15.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_16.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_17.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_18.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_19.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_20.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_21.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_22.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_23.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_24.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_25.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_26.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_27.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_28.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_29.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_30.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_31.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_32.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_33.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_34.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_35.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_36.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_37.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_38.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_39.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_40.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_41.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_42.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_43.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_44.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_45.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_46.webm",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_47.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_48.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_49.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_50.webp",
      "/attached_assets/13. DOWNY Saudi Arabia_FOR WEBSITE/DOWNY_51.webp"
    ],
    description: "This film is a vibrant tribute to fashion across the decades, reimagined through a distinctly Saudi lens. Each scene unfolds like a page in an ornate photo album, transporting us from the 1920s Charleston era to today's modern trends — all connected by the softness, freshness, and vitality that Downy brings to every fabric.\n\nThe storytelling is immersive and dynamic, with each decade presented in a meticulously designed set: a portrait in Diriyah, a traditional coffee salon, 60's brunch in Al-Balad, 70's street style, a kaleidoscope of colorful shmaghs, an 80's walk-in closet, and a contemporary laundry room. Transitions are crafted as visual choreography, seamlessly linking eras in a continuous cinematic flow.\n\nLighting, movement, and sound design elevate each scene into a moment of magic — from the flick of a dress to a storm of petals. Every character is styled with precision, embodying both the fashion of their time and the spirit of Saudi heritage. The result is a commercial that feels like a timeless fashion show in motion, where Downy is the unseen designer keeping every era vivid, fresh, and unforgettable.",
    brand: "Procter & Gamble",
    industry: "Consumer Goods",
    duration: "4 days",
    count: 52,
    featured: true
  },
  {
    id: "olay",
    title: "OLAY",
    category: "SKINCARE",
    image: "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_1.webp",
    assets: [
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_1.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_2.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_3.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_4.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_5.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_6.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_7.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_8.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_9.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_10.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_11.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_12.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_13.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_14.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_15.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_16.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_17.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_18.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_19.1.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_19.2.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_20.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_21.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_22.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_23.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_24.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_25.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_26.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_27.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_28.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_29.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_30.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_31.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_32.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_33.webm",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_34.webp",
      "/attached_assets/14. OLAY Treatment_FOR WEBSITE/OLAY_35.webm"
    ],
    description: "This film is a bold, music-video–inspired celebration of self-assurance, where beauty is defined by choice, clarity, and confidence. Pia — sharp, radiant, and unapologetically herself — becomes the embodiment of Olay's \"Choose What Goes\" ethos, moving fluidly between intimate mirror moments and dynamic lifestyle scenes.\n\nThe rhythm is anchored in contrast: stillness and movement, softness and strength. The mirror is our touchstone, capturing the quiet power of self-recognition, while lifestyle scenes burst with vibrant energy — from commanding a room to playful, magnetic gestures that turn heads effortlessly.\n\nEvery element — from the refined red-and-white set design to the elevated product interactions — feels intentional and modern. The camera remains locked on Pia as the world shifts around her, always placing her at the center of gravity. The result is a visual symphony of poise and empowerment, where Olay isn't just skincare, but the essence of owning who you are, beautifully and without compromise.",
    brand: "Procter & Gamble",
    industry: "Consumer Goods",
    duration: "3 days",
    count: 36,
    featured: true
  },
  {
    id: "bank-of-america",
    title: "BANK OF AMERICA",
    category: "FINANCIAL SERVICES",
    image: "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.001.webp",
    assets: [
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.001.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.002.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.003.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.004.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.005.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.006.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.007.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.008.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.009.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.010.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.011.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.012.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.013.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.014.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.015.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.016.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.017.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.018.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.019.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.020.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.021.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.022.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.023.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.024.webp",
      "/attached_assets/15. BANK OF AMERICA Treatment_FOR WEBSITE/BANK OF AMERICA_Director's Treatment.025.webp"
    ],
    description: "This film for Bank of America is a testament to the power of a single idea, a promise to help individuals, communities, and businesses achieve their goals and fulfill their potential. It's an ode to the American spirit, one of ambition, perseverance, and the unwavering belief that with the right partnership, anything is possible. This project is built on the core philosophy of \"What would you like the power to do?\" and aims to position the bank not just as a financial institution, but as a trusted partner on every journey.\n\nThe story we tell is one of legacy and dedication. We find ourselves at the Puget Sound Naval Shipyard, a place where history and hard work converge. This setting provides a powerful backdrop for a story of craftsmanship, meticulous attention to detail, and the human spirit that fuels American industry. The director's intent is to create a mood and tone that is authentic and visceral, one that connects the bank's services to the real-world stories of people who are making things happen. We want the viewer to feel the grit and determination of the characters, the pride in their work, and the sense of purpose that drives them. The film will capture the essence of a day in the life, the challenges, the small triumphs, and the ultimate payoff of a job well done. By placing the narrative in a location as significant as the Puget Sound Naval Shipyard, we create a powerful and emotional connection between the brand and the fabric of American life, reinforcing Bank of America's role in helping those who build, create, and innovate.",
    brand: "Bank of America",
    industry: "Financial Services",
    duration: "4 days",
    count: 25,
    featured: true
  },


  {
    id: "tiger-beer",
    title: "TIGER BEER",
    category: "BEVERAGE",
    image: "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.001.webp",
    assets: [
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.001.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.002.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.003.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.004.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.005.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.006.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.007.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.008.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.009.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.010.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.011.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.012.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.013.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.014.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.015.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.016.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.017.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.018.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.019.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.020.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.021.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.022.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.023.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.024.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.025.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.026.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.027.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.028.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.029.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.030.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.031.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.032.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.033.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.034.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.035.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.036.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.037.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.038.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.039.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.040.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.041.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.042.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.043.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.044.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.045.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.046.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.047.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.048.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.049.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.050.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.055.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.056.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.057.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.058.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.059.webp",
      "/attached_assets/16. TIGER BEER Treatment_FOR WEBSITE/TIGER BEER - Christopher Hill_Treatment_V2.060.webp"
    ],
    description: "\"You gotta have presence on the court. Presence like a cheetah rather than a chimp. Sure, they both got it, but Chimpy gotta jump around to get it. The shy cheetah moves with total nonchalance, stickin' it to them in his sexy, slow strut. Me? I play like a cheetah.\"\n\nThis monologue from Basketball Diaries is the touchstone of the treatment for Tiger Beer: Uncaged. The confidence and fortitude that comes with unleashing our inner spirit, inner tiger, amassing the courage to believe in ourselves and walking through the valley of new, unexpected challenges is unparalleled. It's being beaten on the anvil of life that really shapes us into who we're meant to be. It's basically supercharge our inner drive and to go balls to the wall for whatever we believe in, to own up to who we really are. Only when we take run a wrecking ball through our reluctance to step out of our comfort zone do we set ourselves on the path of self-discovery and revelation. We have to take that next step into the unknown, however risky.\n\nTiger Beer: Uncaged was designed to be visually commanding. The aim was to shock and awe the audience with an audio-visual spectacle that oozed energy and verve. It had to have a dark, sensual beauty embedded with a bold, playful mood, but one that wouldn't come across as pretentious or self-indulgent. Our purposeful intent was to sweep the audience into the meticulously designed and color drenched world of the film, to have them embrace its effervescent neons, hyper-modern art and enigmatic characters. It had to push the boundaries, both visually and aurally. Ultimately, the film had to feel coherent and stimulate the viewers' senses through its cinematic theatrics in a manner that felt authentic and avant-garde.",
    brand: "Heineken Asia Pacific",
    industry: "Beverage",
    duration: "2 days",
    count: 56,
    featured: true
  },

  {
    id: "united-nations-pride-in-peace",
    title: "UNITED NATIONS - PRIDE IN PEACE",
    category: "GLOBAL INITIATIVE",
    image: "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.001.webp",
    assets: [
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.001.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.002.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.003.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.004.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.005.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.006.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.007.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.008.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.009.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.010.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.011.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.012.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.013.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.014.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.015.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.016.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.017.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.018.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.019.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.020.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.021.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.022.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.023.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.024.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.025.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.026.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.027.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.028.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.029.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.030.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.031.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.032.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.033.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.034.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.035.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.036.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.037.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.038.webp",
      "/attached_assets/17. UNITED NATIONS Treatment_FOR WEBSITE/UNITED NATIONS - Pride In Peace.039.webp"
    ],
    description: "The blue helmets, or the Peacekeepers as they're formally christened, carry out incredibly perilous and honourable missions wherever they're deployed. United Nations: Pride In Peace was a film that would salute Bangladeshi Peacekeepers stationed in Bangladesh and the Congo. The idea was to film an intimate, personal story that would draw the viewer into the lives of both these brave soldiers and the people who care about them back home, concurrently highlighting the advanced training these Peacekeepers receive, the magnitude of Bangladesh's contribution to the overall Peacekeeping force, the pride that comes with service, and the grueling sacrifices that are made.\n\nThe director wanted to immerse himself and his crew in the lives of the Bangladeshi people to tell this story - at home in Dhaka receiving education, their training in Dhaka and Sylhet, and their deployment overseas in Central Africa. The power of this story lay in the access to real life scenarios and the honesty in the storytelling. Everything about their lives and missions is unexpected, every situation is spontaneous. There was no need to embellish an already compelling story. Everything about it was real. And that's how we wanted to keep it.",
    brand: "United Nations",
    industry: "Global Organization",
    duration: "3 days",
    count: 39,
    featured: true
  }
];